### ISSUE TITLE
Display of borders on tables is too "white"

### ISSUE THREAD

**Issue by sbts** [ntoff/Octoprint-CyborgTheme#26]
The sample screenshot shown in the repo displays table borders like this....
![image](https://user-images.githubusercontent.com/11002795/36070677-1d5718bc-0f3b-11e8-8237-b798cae50a8a.png)
However with current Octoprint and Plugin I see this....
![image](https://user-images.githubusercontent.com/11002795/36070684-481cdde8-0f3b-11e8-96e9-7a109d2379e2.png)

As you can see the current table borders are VERY standout, whereas the original is reasonably subdued.
I personally prefer the more subdued look as the controls themselves provide sufficient  visual grouping.

I haven't yet looked around the rest of the UI, but I MUCH prefer the dark theme. Great Work.

Octoprint version : 1.3.6 on OctoPi 0.14.0
Cyborg version    : 0.1.6
Browser is Current Chrome on Linux Mint

**Comment by ntoff** [comment]
As the cyborg theme is now part of the themeify plugin https://github.com/Birkbjo/OctoPrint-Themeify I've more or less handed it all over to that plugin's developer. I just keep forgetting to remove the standalone version from octoprint's plugin repository, which I fixed by requesting it's removal right now before I forget again. Any fixes will happen over in the Themeify version so please switch to that instead, sorry for any inconvenience.

**Comment by sbts** [comment]
@ntoff No problem.
I'm glad to have at least helped remind you to remove it from the plugin repo ;-)

**Comment by ntoff** [comment]
Yeah, it's one of those things that's out of sight out of mind. :( 

I might also update my readme thing to point to its new location
